### ISSUE TITLE
Multiple challenges

### ISSUE THREAD

**Issue by lightalloy** [lightalloy/days-of-code-bot#15]
It should be possible to conduct many challenges with the help of the bot.  
Each challenge is configured by the challenge admin, the settings are: `start_date`, `end_date`, `tag`, and `chat_id`. 
I'll create more issues for the steps of this task.

- [ ] Challenges db structure #16  
- [ ] User participations db structure #17
- [ ] Setting up a challenge #18 
- [ ] User registration #19 
- [ ] Challenge comments #20 
- [ ] Statistics #21
